
##########
# Copyright (c) 2022 Darkosto Entertainment LLC
#
# All rights reserved.
##########
[modules]

	[modules.resources]
		enabled = false

		[modules.resources.gold]

			[modules.resources.gold.gear]
				enabled = true

		[modules.resources.diamond]

			[modules.resources.diamond.gear]
				enabled = true

		[modules.resources.iron]

			[modules.resources.iron.gear]
				enabled = true

