##########
# Copyright (c) 2022 Darkosto Entertainment LLC
#
# All rights reserved.
##########


[Marble]
	#Enable/disable all marble related blocks
	generate = true

[Limestone]
	#Enable/disable all limestone related blocks
	generate = true

[Basalt]
	#Enable/disable all basalt related blocks
	generate = true

