##########
# Copyright (c) 2022 Darkosto Entertainment LLC
#
# All rights reserved.
##########


#General configuration options.
[General]
	#Should Growth Accelerators use animated textures?
	animatedGrowthAccelerators = true

